### ISSUE TITLE
토큰을 이용한(JWT) 인증절차에 대한 고민

### ISSUE THREAD

**Issue by barongun** [barongun/2DO#1]
기본적인 절차로는
1. 로그인 성공 시 토큰 전달
2. 토큰 만료 시 `401` 에러 후 로그인 페이지 이동

토큰 refresh 를 할 수 있다면 어떻게?
1. 사용자가 기간 연장 버튼 클릭? (주로 은행권 홈페이지에서 볼 수 있음.)
2. 자동으로 연장?
자동으로 연장 된다면 자동연장 규칙은?

**Comment by ChangJoo-Park** [comment]
사용자가 api 요청 -> 서버가 토큰이 만료됨을 클라이언트에 반환 -> 클라이언트는 리프레시 토큰을 서버에 전달해서 jwt 갱신 -> 리프레시 토큰이 만료되면 로그아웃, 토큰이 갱신되면 갱신후 재요청

**Comment by ChangJoo-Park** [comment]
이렇게 하면 자동으로 갱신되지않을까요

**Comment by ChangJoo-Park** [comment]
사용 연장 버튼도 같은 순서로 작동할거같은데 자동으로 하냐 수동으로 하냐의 차이일거 같아요 오히려 사용연장이 필요한 상태인지 항상 알수 없는 단점이 있을거같읍니다

**Comment by barongun** [comment]
@LeoHeo 정답을 알려줘!

**Comment by LeoHeo** [comment]
[spring-security-oauth2-jose](https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#spring-security-oauth2-jose)
[Java JWT](https://github.com/jwtk/jjwt)

java의 JWT 토큰 라이브러리들 입니다.

**Comment by barongun** [comment]
@ChangJoo-Park 의견 감사합니다. 막혔던 부분이 리프레시 토큰을 계속 줘야 하나? 에 대한 부분이었는데 조금 풀리는 부분이 있는거 같습니다. 
그리고 현황 대시보드 기능이 있는지라, 제가 생각하기에도 `사용연장버튼` 은 제가 만드려고 하는 시스템에는 어울리지 않네요.

**Comment by barongun** [comment]
방식은 대략 이런 방식으로 정할 것 같습니다.
1. 리프레시 토큰 없이 단일 토큰을 생성한다.
2. 토큰 안에 있는 expire date 를 요청 시마다 판단하여 서버 설정으로 x분 이하로 남았을 경우 토큰을 교체해준다.(사용하고 있다는 증거이니..)
3. 화면은 교체된 토큰으로 사용한다.
4. 만약 요청을 했는데 토큰의 expire date가 지난 후 요청이라면 기존과 마찬가지로 로그인 화면으로 이동시킨다.

기존에 쿠키 방식도 만료시간이 종료되면 로그인 페이지로 이동을 하는 방식이니,
계속 사용 중일 때만 사용중이라 간주하고 연장을 시켜주면 될 것 같습니다.

도움 주셔서 감사합니다 @ChangJoo-Park 님 @LeoHeo 님!
